queue_rules:
  - name: default
    conditions:
      - 'check-success=ci/circleci: job_required_for_mergify'
pull_request_rules:
  - name: automatically merge labeled
    conditions:
      - label=ready
      - 'check-success=ci/circleci: job_required_for_mergify'
    actions:
      review:
        type: APPROVE
      queue:
        name: default
      delete_head_branch: {}
