version: 2.1

jobs:


  release:
    docker:
      - image: "alpine:latest"
    resource_class: small
    steps:
      - run:
          command: exit 0

  job_required_for_mergify:
    docker:
      - image: "alpine:latest"
    resource_class: small
    steps:
      - run:
          command: exit 0
          
  release_check:
    docker:
      - image: "cimg/base:2022.08"
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check most recent main is released
          command: |
            [[ $(git log -1 main --pretty=%B) =~ ^.*Released$ ]]

  
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - release_check:
          filters:
            branches:
              ignore:
                - main
      - job_required_for_mergify:
          filters:
            branches:
              ignore:
                - main
      - release:
          filters:
            branches:
              only: main

